### ISSUE TITLE
The app closes when I use ctrl + v

### ISSUE THREAD

**Issue by reinaldogpn** [LilithRainbows/HabboAirForLinux#5]
The client closes when I copy something from another window and paste on Habbo window, don't know why.

Ps.: tried ctrl + v and to paste by clicking on the chat bar, the client closes on both ways.

**Comment by alinpr18** [comment]
> The client closes when I copy something from another window and paste on Habbo window, don't know why.
> 
> Ps.: tried ctrl + v and to paste by clicking on the chat bar, the client closes on both ways.

Recommend install Bottles from flatpak, works fine, you just have to install adobe-air dependencies and ready

**Comment by reinaldogpn** [comment]
> > The client closes when I copy something from another window and paste on Habbo window, don't know why.
> > 
> > Ps.: tried ctrl + v and to paste by clicking on the chat bar, the client closes on both ways.
> 
> Recommend install Bottles from flatpak, works fine, you just have to install adobe-air dependencies and ready

Nice! Didn't know bottles yet, thanks for the suggestion, works just fine. 😊

**Comment by LilithRainbows** [comment]
Fixed!
