### ISSUE TITLE
The application descriptor could not be found for this application. Try reinstalling or contact the publisher for assistance.

### ISSUE THREAD

**Issue by gabrielpacheco23** [LilithRainbows/HabboAirForLinux#7]
Got this error after trying to run HabboLauncher.sh:

"The application descriptor could not be found for this application. Try reinstalling or contact the publisher for assistance."

But I've already installed Adobe AIR.

**Comment by LilithRainbows** [comment]
Hi, sorry for the delay.
Fixed, run this command from Terminal:
```sh
bash -c "$(wget -q -O- https://github.com/LilithRainbows/HabboAirForLinux/raw/main/Install.sh)"
```
